#!/bin/bash

# How to use:
# Publish app: ./firebase-publish

appFolder=app

echo -n "Type whats new in this version (optional): "
read releaseNotes

echo "release notes : $releaseNotes"

echo "$releaseNotes" > releasenotes.txt
echo "Publishing app..."

./gradlew incrementVersionCode --console=plain

curl --location --request POST 'https://hooks.slack.com/services/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' \
--header 'Content-type: application/json' \
--data-raw '{"text":"Hello, World!"}'