package uddug.com.naukoteka.presentation.chat_flow.media

import moxy.InjectViewState
import toothpick.InjectConstructor
import uddug.com.domain.entities.MediaEntity
import uddug.com.naukoteka.global.base.BasePresenterImpl
import uddug.com.naukoteka.navigation.AppRouter


@InjectConstructor
@InjectViewState
class MediaPresenter(val router: AppRouter) : BasePresenterImpl<MediaView>() {

    private val listOfMedia = listOf(
        MediaEntity("https://avatanplus.com/files/resources/mid/5c00f2aac915316763b3eb48.png"),
        MediaEntity("https://seoportal.net/images/articles/png.png"),
        MediaEntity("https://upload.wikimedia.org/wikipedia/commons/4/47/PNG_transparency_demonstration_1.png"),
        MediaEntity("https://avatanplus.com/files/resources/mid/5c00f2aac915316763b3eb48.png"),
        MediaEntity("https://seoportal.net/images/articles/png.png"),
        MediaEntity("https://upload.wikimedia.org/wikipedia/commons/4/47/PNG_transparency_demonstration_1.png"),
        MediaEntity("https://avatanplus.com/files/resources/mid/5c00f2aac915316763b3eb48.png"),
        MediaEntity("https://seoportal.net/images/articles/png.png"),
        MediaEntity("https://upload.wikimedia.org/wikipedia/commons/4/47/PNG_transparency_demonstration_1.png"),
        MediaEntity("https://avatanplus.com/files/resources/mid/5c00f2aac915316763b3eb48.png"),
        MediaEntity("https://seoportal.net/images/articles/png.png"),
        MediaEntity("https://upload.wikimedia.org/wikipedia/commons/4/47/PNG_transparency_demonstration_1.png"),
        MediaEntity("https://avatanplus.com/files/resources/mid/5c00f2aac915316763b3eb48.png"),
        MediaEntity("https://seoportal.net/images/articles/png.png"),
        MediaEntity("https://upload.wikimedia.org/wikipedia/commons/4/47/PNG_transparency_demonstration_1.png"),
        MediaEntity("https://avatanplus.com/files/resources/mid/5c00f2aac915316763b3eb48.png"),
        MediaEntity("https://seoportal.net/images/articles/png.png"),
        MediaEntity("https://upload.wikimedia.org/wikipedia/commons/4/47/PNG_transparency_demonstration_1.png"),
        MediaEntity("https://avatanplus.com/files/resources/mid/5c00f2aac915316763b3eb48.png"),
        MediaEntity("https://seoportal.net/images/articles/png.png"),
        MediaEntity("https://upload.wikimedia.org/wikipedia/commons/4/47/PNG_transparency_demonstration_1.png"),
        MediaEntity("https://avatanplus.com/files/resources/mid/5c00f2aac915316763b3eb48.png"),
        MediaEntity("https://seoportal.net/images/articles/png.png"),
        MediaEntity("https://upload.wikimedia.org/wikipedia/commons/4/47/PNG_transparency_demonstration_1.png"),
        MediaEntity("https://avatanplus.com/files/resources/mid/5c00f2aac915316763b3eb48.png"),
        MediaEntity("https://seoportal.net/images/articles/png.png"),
        MediaEntity("https://upload.wikimedia.org/wikipedia/commons/4/47/PNG_transparency_demonstration_1.png"),
        MediaEntity("https://avatanplus.com/files/resources/mid/5c00f2aac915316763b3eb48.png"),
        MediaEntity("https://seoportal.net/images/articles/png.png"),
        MediaEntity("https://upload.wikimedia.org/wikipedia/commons/4/47/PNG_transparency_demonstration_1.png"),
        MediaEntity("https://avatanplus.com/files/resources/mid/5c00f2aac915316763b3eb48.png"),
        MediaEntity("https://seoportal.net/images/articles/png.png"),
        MediaEntity("https://upload.wikimedia.org/wikipedia/commons/4/47/PNG_transparency_demonstration_1.png"),
        MediaEntity("https://avatanplus.com/files/resources/mid/5c00f2aac915316763b3eb48.png"),
        MediaEntity("https://seoportal.net/images/articles/png.png"),
        MediaEntity("https://upload.wikimedia.org/wikipedia/commons/4/47/PNG_transparency_demonstration_1.png"),
        MediaEntity("https://avatanplus.com/files/resources/mid/5c00f2aac915316763b3eb48.png"),
        MediaEntity("https://seoportal.net/images/articles/png.png"),
        MediaEntity("https://upload.wikimedia.org/wikipedia/commons/4/47/PNG_transparency_demonstration_1.png"),
        MediaEntity("https://avatanplus.com/files/resources/mid/5c00f2aac915316763b3eb48.png"),
        MediaEntity("https://seoportal.net/images/articles/png.png"),
        MediaEntity("https://upload.wikimedia.org/wikipedia/commons/4/47/PNG_transparency_demonstration_1.png"),
        MediaEntity("https://avatanplus.com/files/resources/mid/5c00f2aac915316763b3eb48.png"),
        MediaEntity("https://seoportal.net/images/articles/png.png"),
        MediaEntity("https://upload.wikimedia.org/wikipedia/commons/4/47/PNG_transparency_demonstration_1.png"),
        MediaEntity("https://avatanplus.com/files/resources/mid/5c00f2aac915316763b3eb48.png"),
        MediaEntity("https://seoportal.net/images/articles/png.png"),
        MediaEntity("https://upload.wikimedia.org/wikipedia/commons/4/47/PNG_transparency_demonstration_1.png"),
        MediaEntity("https://avatanplus.com/files/resources/mid/5c00f2aac915316763b3eb48.png"),
        MediaEntity("https://seoportal.net/images/articles/png.png"),
        MediaEntity("https://upload.wikimedia.org/wikipedia/commons/4/47/PNG_transparency_demonstration_1.png"),
        MediaEntity("https://avatanplus.com/files/resources/mid/5c00f2aac915316763b3eb48.png"),
        MediaEntity("https://seoportal.net/images/articles/png.png"),
        MediaEntity("https://upload.wikimedia.org/wikipedia/commons/4/47/PNG_transparency_demonstration_1.png"),
        MediaEntity("https://avatanplus.com/files/resources/mid/5c00f2aac915316763b3eb48.png"),
        MediaEntity("https://seoportal.net/images/articles/png.png"),
        MediaEntity("https://upload.wikimedia.org/wikipedia/commons/4/47/PNG_transparency_demonstration_1.png"),
        MediaEntity("https://avatanplus.com/files/resources/mid/5c00f2aac915316763b3eb48.png"),
        MediaEntity("https://seoportal.net/images/articles/png.png"),
        MediaEntity("https://upload.wikimedia.org/wikipedia/commons/4/47/PNG_transparency_demonstration_1.png"),
        MediaEntity("https://avatanplus.com/files/resources/mid/5c00f2aac915316763b3eb48.png"),
        MediaEntity("https://seoportal.net/images/articles/png.png"),
        MediaEntity("https://upload.wikimedia.org/wikipedia/commons/4/47/PNG_transparency_demonstration_1.png"),
        MediaEntity("https://avatanplus.com/files/resources/mid/5c00f2aac915316763b3eb48.png"),
        MediaEntity("https://seoportal.net/images/articles/png.png"),
        MediaEntity("https://upload.wikimedia.org/wikipedia/commons/4/47/PNG_transparency_demonstration_1.png"),
        MediaEntity("https://avatanplus.com/files/resources/mid/5c00f2aac915316763b3eb48.png"),
        MediaEntity("https://seoportal.net/images/articles/png.png"),
        MediaEntity("https://upload.wikimedia.org/wikipedia/commons/4/47/PNG_transparency_demonstration_1.png"),
        MediaEntity("https://avatanplus.com/files/resources/mid/5c00f2aac915316763b3eb48.png"),
        MediaEntity("https://seoportal.net/images/articles/png.png"),
        MediaEntity("https://upload.wikimedia.org/wikipedia/commons/4/47/PNG_transparency_demonstration_1.png"),
        MediaEntity("https://avatanplus.com/files/resources/mid/5c00f2aac915316763b3eb48.png"),
        MediaEntity("https://seoportal.net/images/articles/png.png"),
        MediaEntity("https://upload.wikimedia.org/wikipedia/commons/4/47/PNG_transparency_demonstration_1.png"),
        MediaEntity("https://avatanplus.com/files/resources/mid/5c00f2aac915316763b3eb48.png"),
        MediaEntity("https://seoportal.net/images/articles/png.png"),
        MediaEntity("https://upload.wikimedia.org/wikipedia/commons/4/47/PNG_transparency_demonstration_1.png"),
        MediaEntity("https://avatanplus.com/files/resources/mid/5c00f2aac915316763b3eb48.png"),
        MediaEntity("https://seoportal.net/images/articles/png.png"),
        MediaEntity("https://upload.wikimedia.org/wikipedia/commons/4/47/PNG_transparency_demonstration_1.png"),
        MediaEntity("https://avatanplus.com/files/resources/mid/5c00f2aac915316763b3eb48.png"),
        MediaEntity("https://seoportal.net/images/articles/png.png"),
        MediaEntity("https://upload.wikimedia.org/wikipedia/commons/4/47/PNG_transparency_demonstration_1.png"),
        MediaEntity("https://avatanplus.com/files/resources/mid/5c00f2aac915316763b3eb48.png"),
        MediaEntity("https://seoportal.net/images/articles/png.png"),
        MediaEntity("https://upload.wikimedia.org/wikipedia/commons/4/47/PNG_transparency_demonstration_1.png"),
        MediaEntity("https://avatanplus.com/files/resources/mid/5c00f2aac915316763b3eb48.png"),
        MediaEntity("https://seoportal.net/images/articles/png.png"),
        MediaEntity("https://upload.wikimedia.org/wikipedia/commons/4/47/PNG_transparency_demonstration_1.png"),
        MediaEntity("https://avatanplus.com/files/resources/mid/5c00f2aac915316763b3eb48.png"),
        MediaEntity("https://seoportal.net/images/articles/png.png"),
        MediaEntity("https://upload.wikimedia.org/wikipedia/commons/4/47/PNG_transparency_demonstration_1.png"),
        MediaEntity("https://avatanplus.com/files/resources/mid/5c00f2aac915316763b3eb48.png"),
        MediaEntity("https://seoportal.net/images/articles/png.png"),
        MediaEntity("https://upload.wikimedia.org/wikipedia/commons/4/47/PNG_transparency_demonstration_1.png"),
        MediaEntity("https://avatanplus.com/files/resources/mid/5c00f2aac915316763b3eb48.png"),
        MediaEntity("https://seoportal.net/images/articles/png.png"),
        MediaEntity("https://upload.wikimedia.org/wikipedia/commons/4/47/PNG_transparency_demonstration_1.png"),
        MediaEntity("https://avatanplus.com/files/resources/mid/5c00f2aac915316763b3eb48.png"),
        MediaEntity("https://seoportal.net/images/articles/png.png"),
        MediaEntity("https://upload.wikimedia.org/wikipedia/commons/4/47/PNG_transparency_demonstration_1.png"),
        MediaEntity("https://avatanplus.com/files/resources/mid/5c00f2aac915316763b3eb48.png"),
        MediaEntity("https://seoportal.net/images/articles/png.png"),
        MediaEntity("https://upload.wikimedia.org/wikipedia/commons/4/47/PNG_transparency_demonstration_1.png"),
        MediaEntity("https://avatanplus.com/files/resources/mid/5c00f2aac915316763b3eb48.png"),
        MediaEntity("https://seoportal.net/images/articles/png.png"),
        MediaEntity("https://upload.wikimedia.org/wikipedia/commons/4/47/PNG_transparency_demonstration_1.png"),
        MediaEntity("https://avatanplus.com/files/resources/mid/5c00f2aac915316763b3eb48.png"),
        MediaEntity("https://seoportal.net/images/articles/png.png"),
        MediaEntity("https://upload.wikimedia.org/wikipedia/commons/4/47/PNG_transparency_demonstration_1.png"),
        MediaEntity("https://avatanplus.com/files/resources/mid/5c00f2aac915316763b3eb48.png"),
        MediaEntity("https://seoportal.net/images/articles/png.png"),
        MediaEntity("https://upload.wikimedia.org/wikipedia/commons/4/47/PNG_transparency_demonstration_1.png"),
        MediaEntity("https://avatanplus.com/files/resources/mid/5c00f2aac915316763b3eb48.png"),
        MediaEntity("https://seoportal.net/images/articles/png.png"),
        MediaEntity("https://upload.wikimedia.org/wikipedia/commons/4/47/PNG_transparency_demonstration_1.png"),
    )

    override fun onFirstViewAttach() {
        super.onFirstViewAttach()
        viewState.showMedia(listOfMedia)
    }

    fun exit() {
        router.exit()
    }
}